import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const targetPath = resolve(
  process.cwd(),
  'src/environments/environment.production.ts'
);

const apiKey = process.env.GIPHY_API_KEY || 'KEY_LOCAL';
const companyName = process.env.COMPANY_NAME || 'Gifs';
const companyName2 = process.env.COMPANY_NAME2 || 'App';
const companySlogan = process.env.COMPANY_SLOGAN || 'The best GIFs in the world';
const profileName = process.env.PROFILE_NAME || 'YOUR_NAME';
const profileInitials = process.env.PROFILE_INITIALS || 'YN';

const envFile = `// This file is AUTO-GENERATED by scripts/set-env.mjs.
// It is created just before each production build and is NOT meant to be edited or committed.

export const environment = {
  production: true,
  companyName: '${companyName}',
  companyName2: '${companyName2}',
  CompanySlogan: '${companySlogan}',

  profileName: '${profileName}',
  profileInitials: '${profileInitials}',

  giphyApiKey: '${apiKey}',
  giphyUrl: 'https://api.giphy.com/v1',
};
`;

writeFileSync(targetPath, envFile, { encoding: 'utf8' });

if (apiKey === 'KEY_LOCAL') {
  console.warn(
    '[set-env] WARNING: GIPHY_API_KEY is not set. Using the "KEY_LOCAL" placeholder.'
  );
}